services:
  app:
    container_name: app
    build:
      dockerfile: docker/production/php/Dockerfile
      context: .
      args:
        app_folder: '/var/www/api.web-artisan.ru'
    volumes:
      - ./storage/app/public:/var/www/api.web-artisan.ru/public/storage
      - ./storage:/var/www/api.web-artisan.ru/storage
      - ./.env:/var/www/api.web-artisan.ru/.env
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      dockerfile: docker/production/nginx/Dockerfile
      context: .
      args:
        app_folder: '/var/www/api.web-artisan.ru'
    volumes:
      - ./storage/app/public:/var/www/api.web-artisan.ru/public/storage
      - ./storage:/var/www/api.web-artisan.ru/storage
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
