services:
  app:
    container_name: app
    build:
      dockerfile: docker/production/php/Dockerfile
      context: .
    volumes:
    - ./storage/app/public:/var/www/public/storage
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      dockerfile: docker/production/nginx/Dockerfile
      context: .
    volumes_from:
      - app
    restart: unless-stopped
    ports:
    - 80:80
