services:
  app:
    container_name: app
    build:
      dockerfile: docker/production/php/Dockerfile
      context: .
      args:
        app_folder: '/var/www/api.example-blog.local'
    volumes:
      - ./storage/app/public:/var/www/api.example-blog.local/public/storage
      - ./storage/app:/var/www/api.example-blog.local/storage/app
      - ./.env:/var/www/api.example-blog.local/.env
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      dockerfile: docker/production/nginx/Dockerfile
      context: .
      args:
        app_folder: '/var/www/api.example-blog.local'
    volumes:
      - ./storage/app/public:/var/www/api.example-blog.local/public/storage
      - ./storage/app:/var/www/api.example-blog.local/storage/app
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
