services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      dockerfile: docker/development/php/Dockerfile
      context: .
      args:
        user: aleksandr_aladin
        uid: 1000
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/api.example-blog.local
    volumes:
      - .:/var/www/api.example-blog.local
      - ./storage/app/public:/var/www/api.example-blog.local/public/storage

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/api.example-blog.local
      - ./storage/app/public:/var/www/api.example-blog.local/public/storage
      - ./docker/development/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  mysql:
    driver: local
